// Die vier Stücke, nach Schwierigkeit. Zeitangaben in Sekunden der Aufnahme.
// Lizenzen und Quellen: siehe CREDITS.md

export const STUECKE = [
  {
    id: 'beethoven7',
    nr: 1,
    titel: '7. Sinfonie, 2. Satz',
    zusatz: 'Allegretto',
    komponist: 'Ludwig van Beethoven',
    ensemble: 'London Symphony Orchestra, Felix Weingartner',
    jahr: '1923/24',
    audio: 'audio/beethoven7.mp3',
    karte: 'beatmaps/beethoven7.json',
    schwierigkeit: 1,
    tutorial: true,
    beschreibung: 'Ruhiger, unerbittlicher Puls. Das Tutorial – bis zum großen Fortissimo, im freien Spiel der ganze Satz.',
    wertungBis: 178.4,
    toleranz: 0.15,
    hinweise: [
      { t: 0.3, text: 'Allegretto – ein Trauermarsch, der es nicht eilig hat', art: 'satz' },
      { t: 5, text: 'Bratschen und Celli: leise, gleichmäßig', art: 'witz' },
      { t: 24, text: 'Nicht schneller werden. Wirklich nicht.', art: 'witz' },
      { t: 48, text: 'Neue Stimmen kommen dazu – Tempo halten', art: 'witz' },
      { t: 96, text: 'Es wächst. Größer schlagen, nicht schneller', art: 'witz' },
      { t: 134, text: 'Fortissimo – das ganze Orchester', art: 'witz' },
      { t: 168, text: 'Durchhalten, gleich kommt das Trio', art: 'witz' },
      { t: 182, text: 'Trio: A-Dur, Klarinetten singen', art: 'satz' },
    ],
  },
  {
    id: 'radetzky',
    nr: 2,
    titel: 'Radetzky-Marsch',
    zusatz: 'op. 228',
    komponist: 'Johann Strauss (Vater)',
    ensemble: '„The President’s Own“ United States Marine Band, John R. Bourgeois',
    jahr: '1992',
    audio: 'audio/radetzky.mp3',
    karte: 'beatmaps/radetzky.json',
    schwierigkeit: 2,
    beschreibung: 'Der Saal klatscht mit – in deinem Tempo, aber mit Verzögerung. Wer abrupt wechselt, verliert das Publikum.',
    toleranz: 0.13,
    klatschen: [[4.6, 63.5], [127.5, 148.3]],
    hinweise: [
      { t: 0.3, text: 'Marschtempo. Der Saal sitzt in den Startlöchern.', art: 'satz' },
      { t: 4.6, text: 'Publikum klatscht mit – Tempo ruhig halten!', art: 'witz' },
      { t: 40, text: 'Leise Stelle: kleiner dirigieren, der Saal folgt', art: 'witz' },
      { t: 64, text: 'Trio: Der Saal schweigt andächtig', art: 'satz' },
      { t: 127.5, text: 'Da capo – jetzt darf der Saal wieder', art: 'witz' },
      { t: 141, text: 'Nicht hetzen, sonst klatscht der Saal ins Leere', art: 'witz' },
    ],
  },
  {
    id: 'brahms5',
    nr: 3,
    titel: 'Ungarischer Tanz Nr. 5',
    zusatz: 'WoO 1',
    komponist: 'Johannes Brahms',
    ensemble: 'Philadelphia Orchestra, Leopold Stokowski',
    jahr: '1917',
    audio: 'audio/brahms5.mp3',
    karte: 'beatmaps/brahms5.json',
    schwierigkeit: 3,
    beschreibung: 'Ständige Tempowechsel. Ein Schlag pro Takt – Stokowski nimmt sich jede Freiheit, du musst mit.',
    toleranz: 0.14,
    hinweise: [
      { t: 0.1, text: 'Allegro – ein Schlag pro Takt', art: 'satz' },
      { t: 6, text: 'Rubato: Stokowski hält nichts von Gleichmaß', art: 'witz' },
      { t: 76, text: 'Hier nimmt sich jeder Kapellmeister Zeit. Du auch.', art: 'witz' },
      { t: 96, text: 'Vivace! Festhalten.', art: 'witz' },
      { t: 140, text: 'Noch einmal von vorn – mit Gefühl', art: 'witz' },
    ],
  },
  {
    id: 'grieg',
    nr: 4,
    titel: 'In der Halle des Bergkönigs',
    zusatz: 'Peer Gynt, op. 46',
    komponist: 'Edvard Grieg',
    ensemble: 'Musopen Symphony',
    jahr: '2012',
    audio: 'audio/grieg.mp3',
    karte: 'beatmaps/grieg.json',
    schwierigkeit: 4,
    beschreibung: 'Das Finale: Accelerando bis zum Kollaps. Zwei Schläge pro Takt, und jeder wird schneller.',
    toleranz: 0.13,
    hinweise: [
      { t: 0.2, text: 'Alla marcia e molto marcato – die Trolle schleichen', art: 'satz' },
      { t: 22, text: 'Pianissimo. Noch merkt keiner was.', art: 'witz' },
      { t: 55, text: 'Sempre accelerando – Peer rennt', art: 'witz' },
      { t: 86, text: 'Più vivo: Die Trolle haben ihn gesehen', art: 'witz' },
      { t: 104, text: 'Fortissimo und schneller, immer schneller', art: 'witz' },
      { t: 128, text: 'Stretto! Der Berg wackelt', art: 'witz' },
      { t: 140, text: 'Kollaps', art: 'satz' },
    ],
  },
];

export const STUECK = Object.fromEntries(STUECKE.map((s) => [s.id, s]));
